### ISSUE TITLE
Extract theme styles from styled-components

### ISSUE THREAD

**Issue by devjmetivier** [dmetivier/tobea-dev#2]
There is a rendering issue on initial page visits that, if a user has their default theme preference set to 'dark' on their computer, there are several styles that don't get propagated to the rest of the UI.

## Need to do
- [x] Extract theme-specific styles from styled components
- [x] Write documentation to denote the classification between theme-specific styles and overall layout

**Comment by dmetivier** [comment]
All items complete.
